# Here the word related to the learn and pronounce module are designed, update this list to add more words in future.
word_list = ["null","eins","zwei","drei","vier","fünf","sechs","sieben","acht","neun","zehn","elf","zwölf","dreizehn","vierzehn","fünfzehn","sechszehn","siebzehn","achtzehn","neunzehn","zwanzig","dreizig","vierzig","fünfzig","sechzig","siebzig","achtzig","neunzig","hundert"]
 
word_list_phonemes = {'null': ['n', 'ʊ', 'l'], 'eins': ['aɪ̯', 'n', 's'], 'zwei': ['t͡s', 'v', 'aɪ̯'], 'drei': ['d', 'r', 'aɪ̯'], 'vier': ['f', 'iː', 'ɐ̯'], 'fünf': ['f', 'ʏ', 'n', 'f'], 'sechs': ['z', 'ɛ', 'ç', 's'], 'sieben': ['z', 'i', 'b', 'n̩'], 'acht': ['a', 'x', 't'], 'neun': ['n', 'ɔ', 'ɪ̯', 'n'], 'zehn': ['t͡s', 'eː', 'n'], 'elf': ['ɛ', 'l', 'f'], 'zwölf': ['t͡s', 'v', 'œ', 'l', 'f'], 'dreizehn': ['d', 'r', 'a', 'ɪ̯', 't͡s', 'eː', 'n'], 'vierzehn': ['f', 'iː', 'r', 't͡s', 'eː', 'n'], 'fünfzehn': ['f', 'ʏ', 'n', 'f', 't͡s', 'eː', 'n'], 'sechszehn': ['z', 'ɛ', 'ç', 's', 't͡s', 'eː', 'n'], 'siebzehn': ['z', 'iː', 'b', 't͡s', 'eː', 'n'], 'achtzehn': ['a', 'x', 't͡s', 'eː', 'n'], 'neunzehn': ['n', 'ɔ', 'ɪ̯', 'n', 't͡s', 'eː', 'n'], 'zwanzig': ['t͡s', 'v', 'aː', 'n', 't͡s', 'ɪ', 'ç'], 'dreizig': ['d', 'r', 'a', 'ɪ̯', 't͡s', 'ɪ', 'ç'], 'vierzig': ['f', 'iː', 'r', 't͡s', 'ɪ', 'ç'], 'fünfzig': ['f', 'ʏ', 'n', 'f', 't͡s', 'ɪ', 'ç'], 'sechzig': ['z', 'ɛ', 'ç', 't͡s', 'ɪ', 'ç'], 'siebzig': ['z', 'iː', 'b', 't͡s', 'ɪ', 'ç'], 'achtzig': ['a', 'x', 't͡s', 'ɪ', 'ç'], 'neunzig': ['n', 'ɔ', 'ɪ̯', 'n', 't͡s', 'ɪ', 'ç'], 'hundert': ['h', 'ʊ', 'n', 'd', 'ɛː', 'ɐ̯', 't']}

# these are top sentence suggested from detusch1 youtube video to learn to prononuce.
top_sentences = ["Das solltest du dir nicht entgehen lassen",
"Mach dir keinen Kopf",
"Ich habe die Nase voll",
"Lass es dir gut gehen",
"Sein Verhalten ist das letzte",
"Das ist icht so mein Ding",
"Was ist hier los",
"Bist du von allen guten geistern verlassen",
"Na das erklärt einiges",
"Mach dich nicht lächerlich",
"Als ob nichts besseres zu tun hätte",
"ich lasse es mal darauf ankommen",
"ich bin gleich bei Ihnen",
"der Zug ist abgefahren",
"wo waren wir stehen geblieben",
"ich bin total ausgerastet",
"das bringt mich auf die Palme",
"verschone mich damit",
"machst du witze",
"schön für dich",
"du schaffst das",
"das kostet ein halbes Vermögen",
"ich melde mich bei dir",
"sollen wir Nummern austauschen",
"kannst du mich anklingeln",
"das ist es nicht Wert",
"reiß dich zusammen",
"hör auf zu jammern",
"ich habe es vermasselt",
"das geschieht dir recht",
"du wolltest ja nicht auf mich hören",
"du glückliche",
"schönen Feierabend",
"Ich muss jetzt langsam mal los",
"komm doch vorbei",
"pass auf dich auf",
"schieß los",
"Das hatte ich gar nicht auf dem Schirm",
"lass gut sein",
"habe ich was verpasst",
"Das geht mir nicht mehr aus dem Kopf",
"Ich bin erledigt",
"das ist eine reine Zeitverschendung",
"du hast gut reden",
"ich verlasse mich auf dich",
"aufgeschoben ist nicht aufgehoben"]

# topic suggestions generated using chatgpt from words obtained from topic modelling 
topic_suggestions = [
    "Stell dich vor.",
    "Erzähle von deinem Tagesablauf.",
    "Beschreibe deine Familie und Freunde.",
    "Berichte über deine Einkaufserfahrungen.",
    "Sprich über deine Hobbys und was du in deiner Freizeit machst.",
    "Erzähle von deinen Reisen und Urlaubserlebnissen.",
    "Beschreibe, was du gerne kochst und welche Gerichte du magst.",
    "Berichte, wie dein Tag war.",
    "Beschreibe dein Zuhause.",
    "Erkläre das Wetter und die Jahreszeiten in deinem Land.",
    "Erzähle von deiner Arbeit oder deinem Studium.",
    "Erkläre deutsche Kultur und Traditionen.",
    "Sprich über Gesundheit und Fitness.",
    "Äußere deine Meinung und Vorlieben zu verschiedenen Themen.",
    "Schreibe einen formellen Brief.",
    "Diskutiere aktuelle Ereignisse in der Welt.",
    "Erzähle von deinen Plänen für die Zukunft.",
    "Beschreibe eine Stadt oder einen Ort, den du besucht hast.",
    "Berichte über das Erlernen von Sprachen.",
    "Diskutiere über soziale Medien und Technologie.",
    "Erkläre die Unterschiede zwischen Stadt- und Landleben.",
    "Beschreibe deine Lieblingsmusik und Musiker.",
    "Sprich über deine Lieblingsfilme und TV-Serien.",
    "Erzähle von deinem Lieblingsbuch.",
    "Diskutiere über Umweltschutz und nachhaltiges Leben.",
    "Beschreibe ein unvergessliches Erlebnis.",
    "Sprich über deine Haustiere oder dein Lieblingstier.",
    "Erzähle von deinen Kindheitserinnerungen.",
    "Berichte über eine sportliche Aktivität, die du magst.",
    "Erkläre, wie du dein Wochenende verbringst.",
    "Beschreibe deinen Traumurlaub.",
    "Sprich über die Vor- und Nachteile des Internets.",
    "Erkläre, wie man gesund bleibt.",
    "Diskutiere über die Bedeutung von Freundschaft.",
    "Erzähle von einem Fest oder einer Feier, die du magst.",
    "Beschreibe deine Lieblingskleidung und deinen Stil.",
    "Sprich über deinen Berufswunsch.",
    "Erzähle von einer Herausforderung, die du gemeistert hast.",
    "Berichte über eine berühmte Person, die du bewunderst.",
    "Beschreibe deine Morgenroutine.",
    "Erkläre die Bedeutung von Bildung in deinem Leben.",
    "Diskutiere über kulturelle Unterschiede.",
    "Sprich über die Rolle der Familie in deinem Leben.",
    "Erzähle von einem Film oder Theaterstück, das du gesehen hast.",
    "Beschreibe ein typisches Gericht aus deinem Land.",
    "Erkläre, warum du Deutsch lernst.",
    "Diskutiere über die Vor- und Nachteile des Autofahrens.",
    "Sprich über die Bedeutung von Kunst und Kultur.",
    "Erzähle von einem Besuch im Museum oder einer Galerie.",
    "Beschreibe, wie man sich auf eine Prüfung vorbereitet.",
    "Erkläre, wie man Stress abbauen kann.",
    "Diskutiere über die Bedeutung von Freizeit.",
    "Sprich über deine Lieblingssportmannschaft.",
    "Erzähle von einem Ausflug in die Natur.",
    "Beschreibe eine historische Persönlichkeit, die dich interessiert.",
    "Erkläre die Bedeutung von Traditionen in deinem Leben.",
    "Diskutiere über die Rolle der Medien in der Gesellschaft.",
    "Sprich über die Herausforderungen des Erwachsenseins.",
    "Erzähle von einem Projekt, an dem du gearbeitet hast.",
    "Beschreibe dein ideales Zuhause.",
    "Erkläre, wie man ein Budget erstellt und einhält.",
    "Diskutiere über die Bedeutung von Technologie in deinem Alltag.",
    "Sprich über die Zukunft der Arbeit.",
    "Erzähle von einem Fest oder Feiertag in deinem Land.",
    "Beschreibe einen Ort, den du in der Zukunft besuchen möchtest.",
    "Erkläre, warum Sport wichtig für dich ist.",
    "Diskutiere über die Vor- und Nachteile von Fernunterricht.",
    "Sprich über den Einfluss von Werbung.",
    "Erzähle von einem Hobby, das du gerne erlernen möchtest.",
    "Beschreibe deine Lieblingsjahreszeit.",
    "Erkläre, wie man eine gesunde Ernährung aufrechterhält.",
    "Diskutiere über die Vor- und Nachteile von Globalisierung.",
    "Sprich über deine Lieblingsbeschäftigungen im Sommer.",
    "Erzähle von einer Party, die du besucht hast.",
    "Beschreibe einen typischen Schultag.",
    "Erkläre die Bedeutung von Pünktlichkeit.",
    "Diskutiere über die Rolle der Wissenschaft in der Gesellschaft.",
    "Sprich über deine Träume und Ziele.",
    "Erzähle von einem besonderen Tag in deinem Leben.",
    "Beschreibe ein Problem, das du gelöst hast.",
    "Erkläre die Bedeutung von Selbstdisziplin.",
    "Diskutiere über die Vorteile des Reisens.",
    "Sprich über deine Lieblingsstadt.",
    "Erzähle von einem besonderen Geschenk, das du erhalten hast.",
    "Beschreibe deine Lieblingsaktivitäten im Winter.",
    "Erkläre, wie man einen guten ersten Eindruck macht.",
    "Diskutiere über die Bedeutung von Teamarbeit.",
    "Sprich über die Vorteile des Lernens einer neuen Sprache.",
    "Erzähle von einem Auslandsaufenthalt.",
    "Beschreibe deine Lieblingsblumen und Pflanzen.",
    "Erkläre die Rolle von Musik in deinem Leben.",
    "Diskutiere über die Herausforderungen des modernen Lebens.",
    "Sprich über die Beziehung zwischen Mensch und Natur.",
    "Erzähle von einem kulturellen Festival, das du besucht hast.",
    "Beschreibe, wie du deine Freizeit planst.",
    "Erkläre die Bedeutung von Respekt in Beziehungen.",
    "Diskutiere über die Rolle der Technologie im Bildungswesen.",
    "Sprich über deine Lieblingsrestaurants und Cafés.",
    "Erzähle von einem kreativen Projekt, an dem du gearbeitet hast."
]
